-- ================================================================
-- Coal Bot — Recovered death_log data
-- Source: corrupted SQLite file (db.sql)
--
-- What was recovered:
--   ✓ All death log reasons (370 entries) — ASCII text survived
--
-- What could NOT be recovered:
--   ✗ User IDs — stored as binary integers, destroyed by UTF-8
--     corruption of the file. All entries use id = '0' (anonymous).
--   ✗ Original cntr order may vary ±1 for entries near page
--     boundaries. Sequential order here is approximate.
--   ✗ balances, levels, reminders, user_stats — binary-only data,
--     no recoverable rows.
--
-- Note: A small number of entries may have a 1-char artifact at
-- the start or end due to adjacent binary data. Review and fix
-- those manually if needed.
-- ================================================================

BEGIN;

INSERT INTO death_log (id, cntr, reason) VALUES ('0', 1, 'why am I so energized and coherent at 4 hours of sleep5');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 2, 'my foot is bleeding. its small. but a lot');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 3, 'assignment 5 part 3 (eclectic roogaroo)');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 4, 'assignment 5 part 2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 5, 'assignment 5+w');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 6, 'killed by cole for being racist');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 7, 'danielle-u');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 8, 'shot by cole with a bow and arrow');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 9, 'anxietyyyyy');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 10, 'marching band comp');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 11, 'lab meeting....');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 12, 'i hate life');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 13, 'cole killed them');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 14, 'might not graduatein');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 15, 'did an os upgrade during the weekday, on release day, and now networking is partially borkedjm');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 16, 'the heater in my house is BROKEN and my fingies are COLD and my bones are cracking like CRAZY0l');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 17, 'student doesn''t know basic variables');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 18, 'slept in...');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 19, 'registration...');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 20, 'racing against time with racing against time');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 21, 'for being dumb f');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 22, 'being a 1212 studentQe');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 23, 'authentication and RWAs and graphic design and literally everything');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 24, 'jsonwebtokensPc');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 25, '#Dr. Najjar again cuz it was checkpoint day and everything keeps breaking...Xb');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 26, 'fixing the bot to work with sql and still be able to give and get the data.#a');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 27, '1213 lab...so boring...)`');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 28, 'WRIP: andy and cole making the bot....1_');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 29, 'gAndy''s ducks have died. Murdered by Danielle.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 30, 'Checkpoint 2 bullshit.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 31, 'Killed by cole');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 32, '/Subway employees.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 33, '#Tableu devs');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 34, 'Locked out.7W');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 35, 'Got confused for a freshman 3x in one hour.#V');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 36, 'midterm...not prepared.EU');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 37, 'Assignment due at 11:59pm and a midterm in the morning...$T');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 38, 'Fell out of their chair..S');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 39, 'Passed out again...still in vegas! R');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 40, 'Passed out in vegas!NQ');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 41, 'Killed by a phantom. and shark. after stealing my [andy''s] barrel');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 42, '4 exams in one week.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 43, '''Dr. Najjar');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 44, 'SPOOKED');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 45, '5haha...funny number.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 46, 'internet again..');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 47, 'Locked in.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 48, '/EXECUTE ORDER 66.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 49, 'Starved');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 50, 'rip knee#D');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 51, 'Not feeling it today :(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 52, 'Spicy Ramen');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 53, 'Holy gage undergraduate admissions center..?');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 54, 'Killed by Cole for saying they have no friends.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 55, 'Death by internet.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 56, 'Mcdonalds...26');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 57, 'Performance (rip their instrument too)%5');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 58, 'Danielle wants them dead.M4');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 59, 'Trying to understanding the Frequency composition by Minoo Dixo.23');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 60, 'struggled to take a second derivative.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 61, 'Murdered by Toya');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 62, 'Students be killin her');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 63, 'Traffic');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 64, 'CThe government Budget cuts.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 65, 'It got worse.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 66, 'Allergic reaction.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 67, 'Murdered by John.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 68, 'Killed by Cole.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 69, 'Murdered by Cole.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 70, '-Random victim...');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 71, 'murdered someone by poisoning.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 72, 'Toya told me to kms');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 73, 'spoke to soon its out again(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 74, 'cole forgot their headphones!');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 75, 'internet is still out');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 76, 'party planningH');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 77, 'pasting images into discord has a 50-50 shot of crashing it');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 78, 'wifi no work');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 79, 'im gonna miss that classC');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 80, 'nobody knows how to pick up a damn phone in this family3');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 81, 'final exam of the class i hate is today');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 82, 'interview3');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 83, 'cant give boomers an inch of technologyE');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 84, 'my laptop has a sleep hotkey that i keep forgetting about');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 85, 'internet,');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 86, 'final project part 2 and 3 and 4');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 87, 'chugged an energy drink');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 88, 'final project...k');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 89, 'my interview time got moved so now i have to lock in for 3 finals AND prepare for an interview');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 90, 'the people i''m proctoring with');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 91, 'me too gurl');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 92, 'I need a cigarette');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 93, 'students.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 94, 'graduation stuff');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 95, 'graduation stuff-');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 96, 'hasnt started their final project');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 97, 'just realized i have to proctor 2 mock interviews');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 98, 'my tummy hurts :(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 99, 'I cant feel my fingers7');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 100, 'taking pictures in cloudy 30 degree weather');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 101, 'internet... again...');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 102, 'worked ~10.5 hours straight');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 103, 'i sense a headache coming');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 104, 'proctoring');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 105, 'queen caught me lacking');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 106, 'plsssssssssssss');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 107, 'lab meeting x2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 108, '0final!');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 109, 'how''d i forget a name');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 110, 'lab meeting.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 111, 'oral final in 30 minw');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 112, 'internet died for ten minutes while i was trying to prep for 3120 final (that i''m certainly going to fail)');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 113, 'finally finished 5236 hw3.....a');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 114, 'my voice died at the end of the interview and homeboys talking about multiple rounds');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 115, 'i got two jabs yesterday afternoon. it took ~12 hours until they started hurting a bit. now they hurt soooooooo much');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 116, 'Sanvi killed them');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 117, 'Sanvi killed meH');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 118, 'thesis approval due EOD and nobody is answering their emailS');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 119, 'just realized im proctoring a mock interview of a linked list question');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 120, 'internet made it two days');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 121, 'my voice is fried and i have an interview tomorrow3');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 122, 'i only have 15 min to present 20 slides!');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 123, 'capstone presentation');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 124, 'i haven''t seen anybody everK');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 125, 'chillssssssss killed me earlier today and now i got econ to do');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 126, 'life.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 127, 'internet made it almost two months');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 128, 'fuck this shit');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 129, 'cole told me to');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 130, 'got asked the same question 5 times in 30 seconds');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 131, 'boredom');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 132, 'fuck google');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 133, 'cant sleep :(2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 134, 'hunger so freaking hungry im so AAAAAH');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 135, 'runestone.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 136, 'sorrows, sorrows, prayers for cole2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 137, 'checkpoint is having errors once again');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 138, 'fuck zoom');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 139, 'nail broke');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 140, 'generosity');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 141, 'no cum on my laude)');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 142, 'academic integrity violations');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 143, 'parents');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 144, 'FUCK late stage capitalismD');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 145, 'i hate sucking up and being a slave to corporate america');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 146, 'on mobile for good measure');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 147, 'everything: the sequel');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 148, 'people');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 149, 'concert week');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 150, 'all of the things');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 151, 'everything');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 152, 'this is the end!');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 153, 'where tf are my crocs');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 154, 'FUCKKKKKKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 155, 'FUUUUUUUUUUUUUUUUUUUUUUdge');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 156, 'rip sleep');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 157, 'stupid dumbass sore ass throata');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 158, 'professor looked right at me when talking to the class about the essay i just bombed');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 159, 'communication, or lack thereof');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 160, 'my mom(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 161, 'i dont like spring semesters');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 162, '-dr whaley''s knee');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 163, 'coles internet');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 164, 'wifi no work8');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 165, 'lost the ball to my piercing on the job site');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 166, 'stats professor');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 167, 'people are weird(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 168, 'aint no way hes following me');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 169, 'fuck that fuck ass presentation');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 170, 'i fucking hate onedrive');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 171, 'i live too far');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 172, 'I<@916574224083189782>''s router');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 173, 'laptop screen died');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 174, 'i fucked myself');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 175, 'fuck this shitL');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 176, 'why didnt anyone tell me tuples are valid keys for dictionaries');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 177, 'WHY DID THE GATEWAY JUST SUDDENLY DIE IT HAS BEEN FINE FOR MONTHS(? YEARS?) AND ALL OF A SUDDEN DECIDED YOU KNOW WHAT? IM NOT DOING ANYTHING UNTIL I GET A FACTORY RESTARTN');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 178, 'internet died at 12:12. I think its a sign we should cancel fully2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 179, 'att lasted until like <t:1769409000:F');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 180, 'managed to get a cut under my fingernail while...K');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 181, 'my sister broke my cup. and everyone knew. but no one told me.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 182, 'cold and possibly sick');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 183, 'biochem class...6');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 184, 'call me Danielle bc I take two Ls in a row');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 185, 'power4');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 186, 'sad that the cats left (they arent dead)3');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 187, 'kprobably a cat or squirrel or something outside5');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 188, 'i chose the wrong degree and now i suffer');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 189, 'cole is genuinely doing like 5 roles tomorrow ;-;');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 190, 'i got called on');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 191, 'cryptography');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 192, 'fuckass textbook');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 193, 'parking pass');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 194, 'twice today, once while in a meeting');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 195, 'what do you thinkU');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 196, 'may have forgotten that i need to buy a parking pass RIP my bank account');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 197, 'brotherS');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 198, 'i think the internet connection was out from 3am to now...............4');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 199, 'att is not making this year look good...-');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 200, 'it took att 18 hours before dying');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 201, 'wtf is a money orderQ');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 202, 'i hit so many solid clips just for my recording software to not work!');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 203, 'ZI want to go home plz');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 204, 'these damn kids');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 205, 'getting clowned left and right by a four year old');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 206, 'melatonin pills dont work');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 207, 'Instagram :(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 208, 'anxious :/');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 209, 'cole just woke up');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 210, 'hurricanes hockey');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 211, 'HEALTH INSURANCE FFSf');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 212, 'forgot my leasing office closes earlier and now have to go last minute Christmas shopping');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 213, 'headacheT');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 214, 'friend didnt get the job they were interviewing and now im sad for them');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 215, 'i have a headacheE');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 216, 'American Healthcare system fml why was I charged $600 </3');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 217, 'leg day');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 218, 'health insurance ffs');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 219, 'me arms hurt');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 220, 'anxiety');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 221, 'meow meow meow meow');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 222, 'sadness');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 223, 'broke now(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 224, 'gonna be broke next semester');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 225, 'phd application');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 226, 'wasted my money trying food');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 227, 'canvas');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 228, 'do people ever learn');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 229, 'ssh keys');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 230, 'family shit]');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 231, 'im gonna fucking lose it how many times do i have to say NOT TO GO UP THE STAIRS(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 232, 'WHY IS THE SILVER BUS IDLINGH');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 233, 'its 37 degrees and im about to walk from cri deck to sac D:');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 234, 'i woke up at 05:30. i fell asleep around 01:30...');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 235, 'ahhhhhh');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 236, 'aws authentication');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 237, 'game dev final project');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 238, 'yeah gang i aint sleeping0');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 239, 'everything, cumulatively all at once');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 240, '/danielles brother8');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 241, 'graduation is tomorrow and idk if im walking0');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 242, 'graduation is tmmr idk what im doing');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 243, 'these kids');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 244, 'wearing gray in the rain');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 245, 'rain8');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 246, 'my freeish trial of adulthood is running out');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 247, 'roommate being roommate');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 248, 'i killed amelia');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 249, 'danielle');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 250, '#test server');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 251, 'servers');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 252, 'oneitC');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 253, 'trying to lockin and study but im no longer in my prime');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 254, 'internetD');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 255, 'two semesters worth down the drain on this fucking house');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 256, 'no more heat');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 257, 'had to tell tas to shut up');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 258, 'taking care of a house4');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 259, 'roommate listening in on me');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 260, 'gas leak');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 261, 'i change my mind, connect sucks');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 262, 'neighbor going at it');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 263, 'dairy');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 264, 'furnace');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 265, 'zoom chat popup thingy2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 266, 'iwhaley, because of olympics hockey and curling');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 267, 'machine learning');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 268, 'this assignment');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 269, 'neighbor');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 270, 'childhood memories');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 271, 'i wanna go home');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 272, 'dinner');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 273, 'cole doesnt know ip');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 274, 'fuckass dust');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 275, 'head hurt');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 276, 'gecko be geckoings');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 277, 'why i dumb');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 278, '3computer is cooking');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 279, 'Danielle');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 280, 'drivers!');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 281, '<@729469417741615194');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 282, 'apostrophes');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 283, 'ms DanielleG');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 284, 'a goddamn saw set up on the kitchen table!');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 285, 'si grand final result');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 286, 'its raining');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 287, 'nlp. im giving up again');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 288, 'windows');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 289, 'i fucking hate nissan');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 290, 'valentines day');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 291, 'this stupid bot');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 292, 'waiting patiently');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 293, 'roommate');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 294, 'sleep');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 295, 'kids');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 296, 'cole server deafened me');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 297, 'im gay');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 298, 'this shit fucking blowsk');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 299, 'proctoring + students + inability to read + inability to listen + inability to show up on time');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 300, 'technology');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 301, 'resumeD');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 302, '@alcoleholic their laptop wanted to drink some dr pepperC');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 303, 'my professor is trying to kill me by boring me to death-');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 304, '<:blame_andy:1470878311709278230');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 305, 'sway');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 306, 'midterm.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 307, 'john x2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 308, 'toya + john');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 309, 'burnt out');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 310, 'these people');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 311, 'you bully :(((((((');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 312, 'ZToya going to a dinner without me on my birthday');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 313, 'students');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 314, 'device');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 315, 'time2');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 316, 'runestone:');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 317, 'i regret drinking that chocolate protein shake');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 318, 'hungover');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 319, 'google cloud');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 320, 'alcohol');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 321, 'school');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 322, 'internet connection');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 323, 'coles tired and its liud');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 324, 'runestone1');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 325, 'midterm dropped my grade by 10 points');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 326, 'BAD BAD BAD BAD EXAM NOOOOOOO FUCKKKKKKKKK NOOOOO PLEASE <:hairpull:1458140575063740622> <:hairpull:1458140575063740622> <:hairpull:1458140575063740622> <:hairpull:1458140575063740622> <:hairpull:1458140575063740622> <:hairpull:1458140575063740622> <:hairpull:1458140575063740622>3');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 327, 'touched my eye after eating hot cheetos');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 328, 'm*n at the gym');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 329, 'lost a baddie today');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 330, 'allergic reaction)');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 331, 'AC is broken and its sooo hot');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 332, 'm*n AT WORK');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 333, 'i feel like a stranger at my own damn home why dont i have any keys to this place');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 334, 'amelia(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 335, 'left my headphones in waxhaw');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 336, 'Cole mean to me for no reason');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 337, 'casey');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 338, 'i hate vms)');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 339, 'm*n who dont wash their handsD');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 340, 'my ipad has a better display than my mac and it kills me');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 341, 'dummy dummy Danielle(');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 342, 'cole, again for good measure');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 343, 'choking');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 344, 'ban drivers');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 345, '!gradescope');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 346, 'nlp test. should have trusted my gut');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 347, 'long ass class');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 348, 'fuck these students');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 349, 'xavier got me');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 350, 'im actually so cold');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 351, 'yall keep airing out dirty laundry in the middle of lab');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 352, 'panicD');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 353, 'yall keep ignoring then repeating the work i already did');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 354, 'that damn midterm');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 355, 'fuckass autocorrect');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 356, 'my legs');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 357, 'i misread the instructions');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 358, 'sticker');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 359, 'shot');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 360, 'lost my earring somewhere');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 361, 'im stupid');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 362, 'typo.');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 363, 'the wrong nlp pdf report submtited');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 364, 'toya');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 365, 'zip ties');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 366, 'cables');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 367, 'sorority');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 368, 'ITS SO HOT');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 369, 'bombing children');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 370, 'professor');
INSERT INTO death_log (id, cntr, reason) VALUES ('0', 371, 'internet');

COMMIT;
